from fastapi import FastAPI, Request, Header, HTTPException
from fastapi.responses import Response
from fastapi.middleware.cors import CORSMiddleware
import httpx
import base64
import io
import colorsys
from datetime import datetime, timezone

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

app = FastAPI()

# Only allow POST requests from Apple Music web -- the Tampermonkey script
# uses GM_xmlhttpRequest which sends with this origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://music.apple.com"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# In-memory state. Resets on server restart, which is fine because
# Tampermonkey pushes a fresh update within INTERVAL_MS of page load.
current_track = {
    "title":       None,
    "artist":      None,
    "artwork_url": None,
    "is_playing":  False,
    "updated_at":  None,
}

try:
    from config import API_SECRET
except ImportError:
    API_SECRET = None


# ---------------------------------------------------------------------------
# Color extraction
# ---------------------------------------------------------------------------

def get_bg_colors(image_bytes):
    """
    Extract three visually distinct colors from the album artwork.

    The palette is quantized to 16 colors, then sorted by vividness
    (saturation * brightness). Colors closer than 36 degrees on the hue
    wheel are skipped so the three blobs look distinct instead of merging.

    If the artwork is monochromatic, missing colors are generated by
    rotating the dominant hue by 120 and 240 degrees.
    """
    if not HAS_PIL:
        return [(220, 50, 60), (110, 40, 190), (230, 120, 0)]
    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        img = img.resize((80, 80), Image.LANCZOS)

        quantized = img.quantize(colors=16)
        palette = quantized.getpalette()[:48]

        candidates = []
        for i in range(16):
            r, g, b = palette[i * 3], palette[i * 3 + 1], palette[i * 3 + 2]
            h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
            # Skip near-black, near-white, and very desaturated colors
            if s > 0.15 and v > 0.2:
                candidates.append((r, g, b, h, s * v))

        candidates.sort(key=lambda x: -x[4])

        selected = []
        for r, g, b, h, _ in candidates:
            too_close = any(
                min(abs(h - sh), 1 - abs(h - sh)) < 0.1
                for _, _, _, sh in selected
            )
            if not too_close:
                selected.append((r, g, b, h))
            if len(selected) == 3:
                break

        result = [(r, g, b) for r, g, b, _ in selected]

        if not result:
            result = [(220, 50, 60)]
        base_r, base_g, base_b = result[0]
        bh, bs, bv = colorsys.rgb_to_hsv(base_r / 255, base_g / 255, base_b / 255)
        for offset in [0.35, 0.65]:
            if len(result) >= 3:
                break
            h2 = (bh + offset) % 1.0
            r2, g2, b2 = colorsys.hsv_to_rgb(h2, min(bs + 0.1, 0.9), max(bv, 0.5))
            result.append((int(r2 * 255), int(g2 * 255), int(b2 * 255)))

        return result[:3]
    except Exception:
        return [(220, 50, 60), (110, 40, 190), (230, 120, 0)]


# ---------------------------------------------------------------------------
# API
# ---------------------------------------------------------------------------

@app.post("/now-playing")
async def update_now_playing(request: Request, x_secret: str = Header(None)):
    if API_SECRET and x_secret != API_SECRET:
        raise HTTPException(status_code=403, detail="Forbidden")
    data = await request.json()
    current_track.update({
        "title":       data.get("title"),
        "artist":      data.get("artist"),
        "artwork_url": data.get("artwork_url"),
        "is_playing":  data.get("is_playing", False),
        "updated_at":  datetime.now(timezone.utc).isoformat(),
    })
    return {"ok": True}


@app.get("/now-playing")
async def get_now_playing():
    return current_track


@app.get("/now-playing.svg")
async def get_svg():

    # -----------------------------------------------------------------------
    # Badge appearance -- change these to customize the widget
    # -----------------------------------------------------------------------
    SVG_WIDTH    = 500   # total width in pixels
    SVG_HEIGHT   = 100   # total height in pixels
    ARTWORK_SIZE = 76    # album art square size; keep below SVG_HEIGHT - 24
    BLOB_OPACITY = 0.55  # background blob opacity, 0.0 (invisible) to 1.0
    BLOB_BLUR    = 30    # gaussian blur radius for blobs; higher = softer
    BG_COLOR     = "#0a0a0a"  # base background color
    # -----------------------------------------------------------------------

    title       = current_track.get("title") or "Not playing"
    artist      = current_track.get("artist") or ""
    artwork_url = current_track.get("artwork_url")
    is_playing  = current_track.get("is_playing", False)

    # SVG text does not wrap, so truncate before escaping
    if len(title) > 38:
        title = title[:35] + "..."
    if len(artist) > 34:
        artist = artist[:31] + "..."

    def esc(s):
        return (s.replace("&", "&amp;").replace("<", "&lt;")
                 .replace(">", "&gt;").replace('"', "&quot;"))

    title  = esc(title)
    artist = esc(artist)

    artwork_b64 = None
    bg_colors   = [(220, 50, 60), (110, 40, 190), (230, 120, 0)]

    if artwork_url:
        try:
            async with httpx.AsyncClient(timeout=5) as client:
                r = await client.get(artwork_url)
                if r.status_code == 200:
                    raw = r.content
                    ct  = r.headers.get("content-type", "image/jpeg")
                    artwork_b64 = f"data:{ct};base64,{base64.b64encode(raw).decode()}"
                    bg_colors   = get_bg_colors(raw)
        except Exception:
            pass

    c1, c2, c3 = [f"#{r:02x}{g:02x}{b:02x}" for r, g, b in bg_colors]
    accent = c1  # equalizer bar color follows the dominant artwork color

    # Layout -- artwork flush to the left with equal padding
    art_x  = 12
    art_y  = (SVG_HEIGHT - ARTWORK_SIZE) // 2
    text_x = art_x + ARTWORK_SIZE + 16

    # Equalizer zone starts 90px from the right edge
    eq_start = SVG_WIDTH - 90
    eq_xs    = [eq_start + i * 8 for i in range(5)]
    bar_btm  = SVG_HEIGHT - 18  # fixed bottom anchor for all bars

    artwork_el = (
        f'<image href="{artwork_b64}" x="{art_x}" y="{art_y}" '
        f'width="{ARTWORK_SIZE}" height="{ARTWORK_SIZE}" clip-path="url(#art-clip)"/>'
        if artwork_b64
        else (
            f'<rect x="{art_x}" y="{art_y}" width="{ARTWORK_SIZE}" '
            f'height="{ARTWORK_SIZE}" rx="8" fill="#1e1e1e"/>'
            f'<text x="{art_x + ARTWORK_SIZE // 2}" y="{art_y + ARTWORK_SIZE // 2 + 9}" '
            f'text-anchor="middle" font-size="26" fill="#444">&#9835;</text>'
        )
    )

    # Smooth cubic-bezier easing so blobs drift organically
    ks = "0.45 0 0.55 1;0.45 0 0.55 1;0.45 0 0.55 1;0.45 0 0.55 1"

    bg_blobs = f"""
  <g clip-path="url(#card-clip)">
    <g filter="url(#blob-blur)" opacity="{BLOB_OPACITY}">
      <circle cx="60" cy="50" r="95" fill="{c1}">
        <animate attributeName="cx" values="60;115;40;90;60"    dur="22s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
        <animate attributeName="cy" values="50;82;22;68;50"    dur="19s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
      </circle>
      <circle cx="310" cy="15" r="85" fill="{c2}">
        <animate attributeName="cx" values="310;245;375;275;310" dur="28s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
        <animate attributeName="cy" values="15;78;8;58;15"      dur="24s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
      </circle>
      <circle cx="465" cy="82" r="75" fill="{c3}">
        <animate attributeName="cx" values="465;390;495;425;465" dur="20s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
        <animate attributeName="cy" values="82;22;92;48;82"     dur="26s" repeatCount="indefinite" calcMode="spline" keySplines="{ks}"/>
      </circle>
    </g>
  </g>"""

    if is_playing:
        # Each bar animates with independent height and timing to simulate
        # a frequency spectrum. Height values and durations are intentionally
        # varied so bars don't pulse in sync.
        bar_params = [
            ("10;30;16;10", "1.0s", "0s"),
            ("24;10;28;24", "0.8s", "0.2s"),
            ("18;40;8;18",  "1.2s", "0.05s"),
            ("30;12;22;30", "0.9s", "0.3s"),
            ("14;28;8;14",  "1.1s", "0.15s"),
        ]
        bars = ""
        for x, (heights, dur, begin) in zip(eq_xs, bar_params):
            h0 = int(heights.split(";")[0])
            y_vals = ";".join(str(bar_btm - int(h)) for h in heights.split(";"))
            bars += (
                f'<rect x="{x}" y="{bar_btm - h0}" width="6" height="{h0}" rx="2.5" fill="{accent}">'
                f'<animate attributeName="height" values="{heights}" dur="{dur}" repeatCount="indefinite" begin="{begin}"/>'
                f'<animate attributeName="y"      values="{y_vals}"  dur="{dur}" repeatCount="indefinite" begin="{begin}"/>'
                f'</rect>'
            )
        indicator = bars
    else:
        static_h = [10, 14, 12, 15, 10]
        indicator = "".join(
            f'<rect x="{x}" y="{bar_btm - h}" width="6" height="{h}" rx="2.5" fill="#2e2e2e"/>'
            for x, h in zip(eq_xs, static_h)
        )

    svg = f"""<svg width="{SVG_WIDTH}" height="{SVG_HEIGHT}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <clipPath id="card-clip"><rect width="{SVG_WIDTH}" height="{SVG_HEIGHT}" rx="12"/></clipPath>
    <clipPath id="art-clip"><rect x="{art_x}" y="{art_y}" width="{ARTWORK_SIZE}" height="{ARTWORK_SIZE}" rx="8"/></clipPath>
    <clipPath id="text-clip"><rect x="{text_x}" y="0" width="{eq_start - text_x - 8}" height="{SVG_HEIGHT}"/></clipPath>
    <filter id="blob-blur" x="-60%" y="-60%" width="220%" height="220%">
      <feGaussianBlur stdDeviation="{BLOB_BLUR}"/>
    </filter>
  </defs>

  <rect width="{SVG_WIDTH}" height="{SVG_HEIGHT}" rx="12" fill="{BG_COLOR}"/>
  {bg_blobs}
  {artwork_el}

  <g clip-path="url(#text-clip)">
    <text x="{text_x}" y="{int(SVG_HEIGHT * 0.40)}" font-family="system-ui,-apple-system,sans-serif" font-size="15" font-weight="700" fill="#ffffff">{title}</text>
    <text x="{text_x}" y="{int(SVG_HEIGHT * 0.60)}" font-family="system-ui,-apple-system,sans-serif" font-size="12" fill="#cccccc">{artist}</text>
    <text x="{text_x}" y="{int(SVG_HEIGHT * 0.82)}" font-family="system-ui,-apple-system,sans-serif" font-size="9"  fill="#666666">&#9834; Apple Music</text>
  </g>

  {indicator}
</svg>"""

    return Response(
        content=svg,
        media_type="image/svg+xml",
        headers={
            "Cache-Control": "no-cache, no-store, must-revalidate",
            "Pragma": "no-cache",
            "Expires": "0",
        },
    )
